apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 9999
      targetPort: http
      nodePort: 30999
      protocol: TCP
